name: causal_tutorial_env
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - pip
  - python=3.9
  - nb_conda
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - pytorch
  - pytorch-cuda=11.7
  - pygam
  - lightgbm
  - transformers
  - pip:
    - econml
    - networkx==
    - dowhy==0.11.1
    - gcastle==
    - graphviz
    - causal-learn==0.1.3.3
    - grapl-causal==1.5.1
    - causica==0.2.0
    - catenets==0.2.3
